---
title: "SOTA logit"
author: "WRI Mexico Interns"
date: "10/22/2021"
output: beamer_presentation
header-includes: \usepackage{dcolumn}
---


```{r Setup, include=FALSE}
rm(list=ls()) # borrar todo en la memoria
options(digits = 10) # decimales
options(scipen = 100) # para evitar notacion scientifica que afectaba la leyenda de la grafica
knitr::opts_chunk$set(echo = FALSE) # Para que predeterminadamente no salga el output de los codigos.

#######################
####  Directorio  #####
#######################
#### (Cambiar solo despues del "~/Desktop/ a donde este guardado la carpeta) 
knitr::opts_knit$set(root.dir = "~/Desktop/WRI/SOTA")  # Directorio
getwd()
######################

knitr::opts_chunk$set(out.width = '100%', dpi=300) # Resolucion y tamanio de figuras
knitr::opts_chunk$set(fig.env="figure") # Latex figure environment

# tinytex::install_tinytex() # Por si no está instalado o acualizado correr esta linea.
```


```{r Packages Instalation, include=FALSE}
# Para instalar paquetes que no esten descargados que sean necesarios
lista.de.paquete1 <- c("tidyverse","stargazer", "lmtest", "sandwich")
nuevo.paquete1 <- lista.de.paquete1[!(lista.de.paquete1 %in% 
                                          installed.packages()[,"Package"])]
if(length(nuevo.paquete1)) install.packages(nuevo.paquete1, dependencies = TRUE, force = TRUE)

```

```{r Packages activation, include=FALSE}
library(tidyverse)
library(stargazer)
library(lmtest)
library(sandwich)
```




```{r include=FALSE}
Data <- read.csv("CaseMatching_10.26.21.csv")
```


```{r include=FALSE}
head(Data)
tail(Data)
str(Data)
summary(Data)
```


# SDGs logit:

```{r SDG logit, include=FALSE}
SDG <- glm(Invest_Secured ~ YearsOperation + SDG2_Food + SDG6_Water + SDG7_Energy + SDG11_Cities + SDG12_Consumption + SDG_Other + BusinessPlan_Funding + Team_index + MM_Index + Funding_Grants,
                           family = binomial(link = "logit"),
                           data = Data)
```


```{r echo=FALSE, results='asis'}
stargazer(summary(SDG)["coefficients"], align = T, header = F, font.size = "footnotesize")
```

```{r SDG logit coeftes, include=FALSE}
coeftest(SDG, vcov. = vcovHC, type = "HC1")
```




***




# Buisness model logit:

```{r Buisness model logit, include=FALSE}
Business_Model <- glm(Invest_Secured ~ YearsOperation + BusinessModel_NewVenture + BusinessModel_Finance + BusinessModel_ProjectAccelerator + BusinessPlan_Funding + Team_index + MM_Index + Funding_Grants,
                           family = binomial(link = "logit"),
                           data = Data)
```


```{r echo=FALSE, results='asis'}
stargazer(summary(Business_Model)["coefficients"], header = F, align = T, font.size = "scriptsize", column.sep.width = "0pt")
?stargazer
```


```{r Buisness model logit Output, include=FALSE, results='asis'}
stargazer(coeftest(Business_Model, vcov. = vcovHC, type = "HC1"))
```




***




# Stage logit:

```{r Stage logit, include=FALSE}
Stage <- glm(Invest_Secured ~ YearsOperation + Stage_PilotResearch + Stage_ScaleUpStartUp + BusinessPlan_Funding + Team_index + MM_Index + Funding_Grants,
                           family = binomial(link = "logit"),
                           data = Data)
```


```{r echo=FALSE, results='asis'}
stargazer(summary(Stage)["coefficients"], align = T, header = F, font.size = "footnotesize")
```


```{r Stage logit output, include=FALSE, results='asis'}
coeftest(Stage, vcov. = vcovHC, type = "HC1")
```




***




# Region:

```{r Region logit, include=FALSE}
Region <- glm(Invest_Secured ~ YearsOperation + Region_EAPAC + Region_EU_CenAsia + Region_LATAM_C + Region_MENA + Region_NorthAm + Region_SouthAsia + Region_SSA + Region_Global + Region_Multiple + BusinessPlan_Funding + Team_index + MM_Index + Funding_Grants,
                           family = binomial(link = "logit"),
                           data = Data)
```


```{r echo=FALSE, results='asis'}
stargazer(summary(Region)["coefficients"], align = T, header = F, font.size = "footnotesize")
```


```{r Region logit output, include=FALSE, results='asis'}
coeftest(Region, vcov. = vcovHC, type = "HC1")

```

***



# Partner logit:

```{r Partner logit, include=FALSE}
Partner <- glm(Invest_Secured ~ YearsOperation + Partner_Business + Partner_CSO + Partner_FI + Partner_Gov + Partner_LocalBusiness + Partner_LocalCSO + Partner_LocalFI + Partner_LocalGov + LocalPartner + Platform_Partnerships2030 + BusinessPlan_Funding + Team_index + MM_Index + Funding_Grants,
                           family = binomial(link = "logit"),
                           data = Data)
```


```{r echo=FALSE, results='asis'}
stargazer(summary(Partner)["coefficients"], align = T, header = F, font.size = "footnotesize")
```


```{r Partner logit output, include=FALSE, results='asis'}
coeftest(Partner, vcov. = vcovHC, type = "HC1")
```


***

# Including only significant dummy variables with the remaining ones

```{r include=FALSE}
together <- glm(Invest_Secured ~ YearsOperation + SDG7_Energy + SDG11_Cities + Partner_LocalCSO + BusinessPlan_Funding + Team_index + MM_Index + Funding_Grants + SDG_Other,
               family = binomial(link = "logit"),
               data = Data)
```

```{r echo=FALSE, results='asis'}
stargazer(summary(together)["coefficients"], align = T, header = F, font.size = "footnotesize")
```


***


# Eliminating statistically insignificant coeffcients


```{r include=FALSE}
eliminating <- glm(Invest_Secured ~ YearsOperation + SDG7_Energy + SDG11_Cities + Partner_LocalCSO + BusinessPlan_Funding + SDG_Other,
                family = binomial(link = "logit"),
                data = Data)
```


```{r echo=FALSE, results='asis'}
stargazer(summary(eliminating)["coefficients"], align = T, header = F, font.size = "footnotesize")
```


***


# Graph Percentage of Projects with Secured Investment


```{r include=FALSE}
Data$MM_Index <- factor(Data$MM_Index)
levels(Data$MM_Index)
```


```{r include=FALSE}
Energy <- Data[Data$SDG7_Energy == 1,]

EnergyMM0Fund <- sum(Energy$Invest_Secured & Energy$MM_Index == 0)/length(Energy$MM_Index == 0)

EnergyMM0.2Fund <- sum(Energy$Invest_Secured & Energy$MM_Index == 0.2)/length(Energy$MM_Index == 0.2)

EnergyMM0.4Fund <- sum(Energy$Invest_Secured & Energy$MM_Index == 0.4)/length(Energy$MM_Index == 0.4)

EnergyMM0.6Fund <- sum(Energy$Invest_Secured & Energy$MM_Index == 0.6)/length(Energy$MM_Index == 0.6)

EnergyMM0.8Fund <- sum(Energy$Invest_Secured & Energy$MM_Index == 0.8)/length(Energy$MM_Index == 0.8)

EnergyMM1Fund <- sum(Energy$Invest_Secured & Energy$MM_Index == 1)/length(Energy$MM_Index == 1)
```

```{r include=FALSE}
Maturity <- data.frame(levels(Data$MM_Index), c(EnergyMM0Fund, EnergyMM0.2Fund, EnergyMM0.4Fund,
                         EnergyMM0.6Fund, EnergyMM0.8Fund, EnergyMM1Fund))

colnames(Maturity) <- c("MLevel", "InvSec")

EnergyPlot <- ggplot(Maturity, aes(MLevel, InvSec, color = "Energy")) + 
  geom_line(group = 1)
```













```{r include=FALSE}
Cities <- Data[Data$SDG11_Cities == 1,]

CitiesMM0Fund <- sum(Cities$Invest_Secured & Cities$MM_Index == 0)/length(Cities$MM_Index == 0)

CitiesMM0.2Fund <- sum(Cities$Invest_Secured & Cities$MM_Index == 0.2)/length(Cities$MM_Index == 0.2)

CitiesMM0.4Fund <- sum(Cities$Invest_Secured & Cities$MM_Index == 0.4)/length(Cities$MM_Index == 0.4)

CitiesMM0.6Fund <- sum(Cities$Invest_Secured & Cities$MM_Index == 0.6)/length(Cities$MM_Index == 0.6)

CitiesMM0.8Fund <- sum(Cities$Invest_Secured & Cities$MM_Index == 0.8)/length(Cities$MM_Index == 0.8)

CitiesMM1Fund <- sum(Cities$Invest_Secured & Cities$MM_Index == 1)/length(Cities$MM_Index == 1)
```

```{r include=FALSE}
MaturityC <- data.frame(levels(Data$MM_Index), c(CitiesMM0Fund, CitiesMM0.2Fund, CitiesMM0.4Fund,
                         CitiesMM0.6Fund, CitiesMM0.8Fund, CitiesMM1Fund))

colnames(MaturityC) <- c("MLevel", "InvSec")

CitiesPlot <- ggplot(MaturityC, aes(MLevel, InvSec, color = "Cities")) + 
  geom_line(group = 1)
```











```{r include=FALSE}
BPF <- Data[Data$BusinessPlan_Funding == 1,]

BPFMM0Fund <- sum(BPF$Invest_Secured & BPF$MM_Index == 0)/length(BPF$MM_Index == 0)

BPFMM0.2Fund <- sum(BPF$Invest_Secured & BPF$MM_Index == 0.2)/length(BPF$MM_Index == 0.2)

BPFMM0.4Fund <- sum(BPF$Invest_Secured & BPF$MM_Index == 0.4)/length(BPF$MM_Index == 0.4)

BPFMM0.6Fund <- sum(BPF$Invest_Secured & BPF$MM_Index == 0.6)/length(BPF$MM_Index == 0.6)

BPFMM0.8Fund <- sum(BPF$Invest_Secured & BPF$MM_Index == 0.8)/length(BPF$MM_Index == 0.8)

BPFMM1Fund <- sum(BPF$Invest_Secured & BPF$MM_Index == 1)/length(BPF$MM_Index == 1)
```

```{r include=FALSE}
MaturityB <- data.frame(levels(Data$MM_Index), c(BPFMM0Fund, BPFMM0.2Fund, BPFMM0.4Fund,
                         BPFMM0.6Fund, BPFMM0.8Fund, BPFMM1Fund))

colnames(MaturityB) <- c("MLevel", "InvSec")

BPFPlot <- ggplot(MaturityB, aes(MLevel, InvSec, color = "BPF")) + 
  geom_line(group = 1)
```











```{r include=FALSE}
NBPF <- Data[Data$BusinessPlan_Funding != 1,]

NBPFMM0Fund <- sum(NBPF$Invest_Secured & NBPF$MM_Index == 0)/length(NBPF$MM_Index == 0)

NBPFMM0.2Fund <- sum(NBPF$Invest_Secured & NBPF$MM_Index == 0.2)/length(NBPF$MM_Index == 0.2)

NBPFMM0.4Fund <- sum(NBPF$Invest_Secured & NBPF$MM_Index == 0.4)/length(NBPF$MM_Index == 0.4)

NBPFMM0.6Fund <- sum(NBPF$Invest_Secured & NBPF$MM_Index == 0.6)/length(NBPF$MM_Index == 0.6)

NBPFMM0.8Fund <- sum(NBPF$Invest_Secured & NBPF$MM_Index == 0.8)/length(NBPF$MM_Index == 0.8)

NBPFMM1Fund <- sum(NBPF$Invest_Secured & NBPF$MM_Index == 1)/length(NBPF$MM_Index == 1)
```

```{r include=FALSE}
MaturityN <- data.frame(levels(Data$MM_Index), c(NBPFMM0Fund, NBPFMM0.2Fund, NBPFMM0.4Fund,
                         NBPFMM0.6Fund, NBPFMM0.8Fund, NBPFMM1Fund))

colnames(MaturityN) <- c("MLevel", "InvSec")

NBPFPlot <- ggplot(MaturityN, aes(MLevel, InvSec, color = "w/o Buisness Plan Funding")) + 
  geom_line(group = 1)
```




```{r include=FALSE}
ProjbyMat <- EnergyPlot + 
  geom_line(data = MaturityC, aes(MLevel, InvSec, color = "Cities"), group = 1) +  
  geom_line(data = MaturityB, aes(MLevel, InvSec, color = "Buisness Plan Funding"), group = 1) +
  geom_line(data = MaturityN, aes(MLevel, InvSec, color = "w/o Buisness Plan Funding"), group = 1) +
  xlab("Maturity") +
  ylab("% of projects with secured investment") +
  ggtitle("% Projects with Secured Investment by Maturity") +
  theme(axis.title.x = element_text(color="Black", size=15),
        axis.title.y = element_text(color = " Black", size=15),
        axis.text.x = element_text(size=8),
        axis.text.y = element_text(size=10),
        
        legend.title = element_text(size=10),
        legend.text = element_text(size=8),
        legend.position = "right",
        legend.justification = c(1,1),
        
        plot.title = element_text(color="DarkBlue",
                                  size=14,
                                  family="Courier")) +
       scale_color_manual(name = "Variable", values =
                       c(Energy = "Dark Red",
                           Cities = "Dark Green", `Buisness Plan Funding` = "Dark Blue", `w/o Buisness Plan Funding` = " Dark Orange"))
  
```

```{r echo=FALSE}
ProjbyMat
```

